// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team34FinalAPI.Models;

#nullable disable

namespace Team34FinalAPI.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20240823102505_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.Property<int>("PostCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostCheckId"));

                    b.Property<string>("AdditionalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BrakeLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Brakes")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedByJWSecurity")
                        .HasColumnType("bit");

                    b.Property<decimal>("ClosingKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FuelLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("Handbrake")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Horn")
                        .HasColumnType("bit");

                    b.Property<bool>("Indicators")
                        .HasColumnType("bit");

                    b.Property<bool>("JWMarketingMagnets")
                        .HasColumnType("bit");

                    b.Property<bool>("JackAndWheelSpannerPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("LicenseDiskValid")
                        .HasColumnType("bit");

                    b.Property<bool>("Mirrors")
                        .HasColumnType("bit");

                    b.Property<bool>("OilLeaks")
                        .HasColumnType("bit");

                    b.Property<bool>("ParkLights")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseHooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SeatBelts")
                        .HasColumnType("bit");

                    b.Property<bool>("SpareWheelPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("StrobeLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SunVisor")
                        .HasColumnType("bit");

                    b.Property<bool>("TyreCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("WindscreenWiper")
                        .HasColumnType("bit");

                    b.HasKey("PostCheckId");

                    b.ToTable("PostChecks");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PreChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BrakeLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Brakes")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedByJWSecurity")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FuelLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("Handbrake")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Horn")
                        .HasColumnType("bit");

                    b.Property<bool>("Indicators")
                        .HasColumnType("bit");

                    b.Property<bool>("JWMarketingMagnets")
                        .HasColumnType("bit");

                    b.Property<bool>("JackAndWheelSpannerPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("LicenseDiskValid")
                        .HasColumnType("bit");

                    b.Property<bool>("Mirrors")
                        .HasColumnType("bit");

                    b.Property<bool>("OilLeaks")
                        .HasColumnType("bit");

                    b.Property<decimal>("OpeningKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ParkLights")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseHooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SeatBelts")
                        .HasColumnType("bit");

                    b.Property<bool>("SpareWheelPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("StrobeLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SunVisor")
                        .HasColumnType("bit");

                    b.Property<bool>("TyreCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("WindscreenWiper")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PreChecklists");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("ActivityCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobNo")
                        .HasColumnType("int");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TaskCode")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("StatusId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Rate", b =>
                {
                    b.Property<int>("RateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateID"));

                    b.Property<string>("ApplicableTimePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("RateTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RateID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("RateTypeID");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RateType", b =>
                {
                    b.Property<int>("RateTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateTypeID"));

                    b.Property<string>("RateTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RateTypeID");

                    b.ToTable("RateType");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RefuelVehicle", b =>
                {
                    b.Property<int>("RefuelVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefuelVehicleId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FuelCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FuelQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OilLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("TyreCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyrePressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefuelVehicleId");

                    b.HasIndex("TripId");

                    b.ToTable("RefuelVehicles", (string)null);
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreChecklistId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TravelStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripId");

                    b.HasIndex("BookingID");

                    b.HasIndex("PreChecklistId")
                        .IsUnique();

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("Team34FinalAPI.Models.TripMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCheckId")
                        .HasColumnType("int");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.HasIndex("PostCheckId");

                    b.HasIndex("TripId");

                    b.ToTable("TripMedia", (string)null);
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Project", "Project")
                        .WithMany("Bookings")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Rate", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Project", "Project")
                        .WithMany("Rates")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.RateType", "RateType")
                        .WithMany("Rates")
                        .HasForeignKey("RateTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("RateType");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RefuelVehicle", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Trip", "Trip")
                        .WithMany("RefuelVehicles")
                        .HasForeignKey("TripId")
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Booking", "Booking")
                        .WithMany("Trips")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.PreChecklist", "PreChecklist")
                        .WithOne()
                        .HasForeignKey("Team34FinalAPI.Models.Trip", "PreChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("PreChecklist");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.TripMedia", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.PostCheck", "PostCheck")
                        .WithMany("TripMedia")
                        .HasForeignKey("PostCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.Trip", null)
                        .WithMany("TripMedia")
                        .HasForeignKey("TripId");

                    b.Navigation("PostCheck");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.Navigation("TripMedia");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RateType", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.Navigation("RefuelVehicles");

                    b.Navigation("TripMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
