// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team34FinalAPI.Models;

#nullable disable

namespace Team34FinalAPI.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    partial class VehicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Team34FinalAPI.Models.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colour");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = " Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = " White "
                        },
                        new
                        {
                            Id = 3,
                            Name = " Blue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 5,
                            Name = " Grey"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 7,
                            Name = " Silver"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.InsuranceCover", b =>
                {
                    b.Property<int>("InsuranceCoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceCoverId"));

                    b.Property<string>("InsuranceCoverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceCoverId");

                    b.ToTable("InsuranceCover");

                    b.HasData(
                        new
                        {
                            InsuranceCoverId = 1,
                            InsuranceCoverName = " By Seun"
                        },
                        new
                        {
                            InsuranceCoverId = 2,
                            InsuranceCoverName = "Comprehensive "
                        },
                        new
                        {
                            InsuranceCoverId = 3,
                            InsuranceCoverName = "Third Party Only"
                        },
                        new
                        {
                            InsuranceCoverId = 4,
                            InsuranceCoverName = " Outsurance "
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.LicenseDisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LicenseDisks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicenseExpiryDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 1
                        },
                        new
                        {
                            Id = 2,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 2
                        },
                        new
                        {
                            Id = 3,
                            LicenseExpiryDate = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 3
                        },
                        new
                        {
                            Id = 4,
                            LicenseExpiryDate = new DateTime(2028, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 4
                        },
                        new
                        {
                            Id = 5,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 5
                        },
                        new
                        {
                            Id = 6,
                            LicenseExpiryDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 6
                        },
                        new
                        {
                            Id = 7,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 7
                        },
                        new
                        {
                            Id = 8,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 8
                        },
                        new
                        {
                            Id = 9,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 9
                        },
                        new
                        {
                            Id = 10,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 10
                        },
                        new
                        {
                            Id = 11,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 11
                        },
                        new
                        {
                            Id = 12,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 12
                        },
                        new
                        {
                            Id = 13,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 13
                        },
                        new
                        {
                            Id = 14,
                            LicenseExpiryDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 14
                        },
                        new
                        {
                            Id = 15,
                            LicenseExpiryDate = new DateTime(2028, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 15
                        },
                        new
                        {
                            Id = 16,
                            LicenseExpiryDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 16
                        },
                        new
                        {
                            Id = 17,
                            LicenseExpiryDate = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 17
                        },
                        new
                        {
                            Id = 18,
                            LicenseExpiryDate = new DateTime(2028, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 18
                        },
                        new
                        {
                            Id = 19,
                            LicenseExpiryDate = new DateTime(2027, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 19
                        },
                        new
                        {
                            Id = 20,
                            LicenseExpiryDate = new DateTime(2028, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 20
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.ToTable("VehicleService");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            Description = " The brake was not working",
                            ServiceDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 1
                        },
                        new
                        {
                            ServiceID = 2,
                            Description = " The windows were not closing ",
                            ServiceDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 2
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.ServiceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ServiceDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 1
                        },
                        new
                        {
                            Id = 2,
                            ServiceDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 2
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Available "
                        },
                        new
                        {
                            Id = 2,
                            Name = " Booked "
                        },
                        new
                        {
                            Id = 3,
                            Name = " In For Service "
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"));

                    b.Property<int>("ColourID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuelTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsuranceCoverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleMakeID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelID")
                        .HasColumnType("int");

                    b.HasKey("VehicleID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleID = 1,
                            ColourID = 2,
                            DateAcquired = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "i20",
                            EngineNo = "G4LFPV302509",
                            FuelTypeID = 1,
                            Image = "imageA.jpg",
                            InsuranceCoverID = 2,
                            LicenseExpiryDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hyundai 1",
                            RegistrationNumber = "LN 68 YM GP",
                            StatusID = 1,
                            VIN = "MALBG512LPM254886",
                            VehicleMakeID = 7,
                            VehicleModelID = 1
                        },
                        new
                        {
                            VehicleID = 2,
                            ColourID = 2,
                            DateAcquired = new DateTime(2019, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Extra Cab 2.4 GD-6 RB SRX 6MT ",
                            EngineNo = "2GDC598667",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 1",
                            RegistrationNumber = "JF 72 WJ GP",
                            StatusID = 1,
                            VIN = "AHTJB8DC404730166",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 3,
                            ColourID = 2,
                            DateAcquired = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Extra Cab 2.4 GD-6 RB SRX 6MT",
                            EngineNo = "2GDC765766",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 2,
                            LicenseExpiryDate = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 2",
                            RegistrationNumber = "JT 99 LF GP",
                            StatusID = 1,
                            VIN = "AHTJB3DCX04490835",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 4,
                            ColourID = 2,
                            DateAcquired = new DateTime(2024, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC HILUX 2.4 GD-6 RAIDER 4X4 A/T",
                            EngineNo = "2GDD364709",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 2,
                            LicenseExpiryDate = new DateTime(2028, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 3",
                            RegistrationNumber = "LR 01 CT GP",
                            StatusID = 1,
                            VIN = "AHTKB3CD802676867",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 5,
                            ColourID = 2,
                            DateAcquired = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD6 RB SRX MT (Z50) 2019",
                            EngineNo = "2GDC503748",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 4",
                            RegistrationNumber = "HY 06 DR GP",
                            StatusID = 1,
                            VIN = "AHTJB8DB104579407",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 6,
                            ColourID = 2,
                            DateAcquired = new DateTime(2012, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC, Raider 2.7 D, 4X4, ROPS ",
                            EngineNo = "2KD5635798",
                            FuelTypeID = 1,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2028, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 5",
                            RegistrationNumber = "BT 11 SL GP",
                            StatusID = 1,
                            VIN = "AHTFR22G906054497",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 7,
                            ColourID = 2,
                            DateAcquired = new DateTime(2005, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC",
                            EngineNo = "1KD7486383",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 6",
                            RegistrationNumber = "WZV 941 GP",
                            StatusID = 1,
                            VIN = "AHTEZ39G207010469",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 8,
                            ColourID = 2,
                            DateAcquired = new DateTime(2016, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC, 4X4 ( With Canopy ) ",
                            EngineNo = "2GD0195958",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 7",
                            RegistrationNumber = "FN 57 RR GP",
                            StatusID = 1,
                            VIN = "AHTKB3CD302604992",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 9,
                            ColourID = 2,
                            DateAcquired = new DateTime(2016, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC, 4x4",
                            EngineNo = "2GD0207661",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 8",
                            RegistrationNumber = "FN 57 ST GP",
                            StatusID = 1,
                            VIN = "AHTK3CD202605213",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 10,
                            ColourID = 2,
                            DateAcquired = new DateTime(2017, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "2.8 GD-6DC, 4x4 Auto ( With Canopy ) ",
                            EngineNo = "1GD0252789",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 9",
                            RegistrationNumber = "FV 25 XR GP",
                            StatusID = 1,
                            VIN = "AHTHA3CD403417011",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 11,
                            ColourID = 2,
                            DateAcquired = new DateTime(2017, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD-6RB, SRX 4x2 ",
                            EngineNo = "2GD0284816",
                            FuelTypeID = 1,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 10",
                            RegistrationNumber = "FX 22 YD GP",
                            StatusID = 1,
                            VIN = "AHTJB8DB504573626",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 12,
                            ColourID = 2,
                            DateAcquired = new DateTime(2017, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD-6RB, SRX 4x2 ",
                            EngineNo = "2GD0284247",
                            FuelTypeID = 1,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 11",
                            RegistrationNumber = "FX 23 BX GP",
                            StatusID = 1,
                            VIN = "AHTJB8DB304573608",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 13,
                            ColourID = 2,
                            DateAcquired = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " DC 2.4 GD-6RB SR MT ",
                            EngineNo = "2GDC910427",
                            FuelTypeID = 1,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 2,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 12",
                            RegistrationNumber = "KP 05 MC GP",
                            StatusID = 1,
                            VIN = "AHTJB3DD504527511",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 14,
                            ColourID = 2,
                            DateAcquired = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " DC 2.4 GD6 RB RAI MT ( With Canopy ) ",
                            EngineNo = "2GDD036238",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 2,
                            LicenseExpiryDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 13",
                            RegistrationNumber = "KW 51 TL GP",
                            StatusID = 1,
                            VIN = "AHTJB3DD304529631",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 15,
                            ColourID = 2,
                            DateAcquired = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Extra Cab HiluxXC 2.4 GD6 RBRAI 6MT ( A1P )  ",
                            EngineNo = "2GDD138062",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 2,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 14",
                            RegistrationNumber = "LB 93 JV GP",
                            StatusID = 1,
                            VIN = "AHTJB3DC104496782",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 16,
                            ColourID = 2,
                            DateAcquired = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1.8 XR CVT ",
                            EngineNo = "2ZRW975634",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 2,
                            LicenseExpiryDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 15",
                            RegistrationNumber = "KV 84 DV GP ",
                            StatusID = 1,
                            VIN = "AHTKFBAG500614236",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 17,
                            ColourID = 2,
                            DateAcquired = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC 2.8 GD-6RB, 4x2",
                            EngineNo = "1GD0374210",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota S1",
                            RegistrationNumber = " HH 91 VZ GP ",
                            StatusID = 1,
                            VIN = "AHTGA3DD900968871",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 18,
                            ColourID = 2,
                            DateAcquired = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD-6RB, SRX 4x2 ",
                            EngineNo = "",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2028, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota S2",
                            RegistrationNumber = " FV 69 WP GP ",
                            StatusID = 1,
                            VIN = "",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 19,
                            ColourID = 2,
                            DateAcquired = new DateTime(2005, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD-6RB, SRX 4x2",
                            EngineNo = "2GD0329959",
                            FuelTypeID = 2,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2027, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota S3",
                            RegistrationNumber = "HC 85 FY GP",
                            StatusID = 1,
                            VIN = "AHTJB8DBX04575081",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 20,
                            ColourID = 2,
                            DateAcquired = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " DC DMAX 2.2",
                            EngineNo = "4JK1VT8141",
                            FuelTypeID = 1,
                            Image = "imageB.jpg",
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2028, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Isuzu 1",
                            RegistrationNumber = " ND 836-010",
                            StatusID = 1,
                            VIN = "ACVNRCHR3K1070230",
                            VehicleMakeID = 9,
                            VehicleModelID = 2
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleFuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FuelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FuelName = "Petrol"
                        },
                        new
                        {
                            Id = 2,
                            FuelName = "Diesel"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleMakeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleMakeID");

                    b.ToTable("VehicleMake");

                    b.HasData(
                        new
                        {
                            VehicleMakeID = 1,
                            Name = "Audi"
                        },
                        new
                        {
                            VehicleMakeID = 2,
                            Name = "Brandt BRV"
                        },
                        new
                        {
                            VehicleMakeID = 3,
                            Name = "Citroen"
                        },
                        new
                        {
                            VehicleMakeID = 4,
                            Name = "Ford"
                        },
                        new
                        {
                            VehicleMakeID = 5,
                            Name = "Haval"
                        },
                        new
                        {
                            VehicleMakeID = 6,
                            Name = "Honda"
                        },
                        new
                        {
                            VehicleMakeID = 7,
                            Name = "Hyundai"
                        },
                        new
                        {
                            VehicleMakeID = 8,
                            Name = "Kia"
                        },
                        new
                        {
                            VehicleMakeID = 9,
                            Name = "Isuzu"
                        },
                        new
                        {
                            VehicleMakeID = 10,
                            Name = "Nissan"
                        },
                        new
                        {
                            VehicleMakeID = 11,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelID"));

                    b.Property<int>("VehicleMakeID")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleModelID");

                    b.ToTable("VehicleModel");

                    b.HasData(
                        new
                        {
                            VehicleModelID = 1,
                            VehicleMakeID = 11,
                            VehicleModelName = " Corolla Cross"
                        },
                        new
                        {
                            VehicleModelID = 2,
                            VehicleMakeID = 11,
                            VehicleModelName = " Hilux "
                        },
                        new
                        {
                            VehicleModelID = 3,
                            VehicleMakeID = 9,
                            VehicleModelName = " Izuzu"
                        },
                        new
                        {
                            VehicleModelID = 4,
                            VehicleMakeID = 1,
                            VehicleModelName = " A3"
                        },
                        new
                        {
                            VehicleModelID = 5,
                            VehicleMakeID = 1,
                            VehicleModelName = " A4 "
                        },
                        new
                        {
                            VehicleModelID = 6,
                            VehicleMakeID = 7,
                            VehicleModelName = " Grand i10"
                        },
                        new
                        {
                            VehicleModelID = 7,
                            VehicleMakeID = 7,
                            VehicleModelName = " Venue "
                        },
                        new
                        {
                            VehicleModelID = 8,
                            VehicleMakeID = 7,
                            VehicleModelName = " TUCSON"
                        },
                        new
                        {
                            VehicleModelID = 9,
                            VehicleMakeID = 4,
                            VehicleModelName = " Ranger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
