// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team34FinalAPI.Models;

#nullable disable

namespace Team34FinalAPI.Migrations.RateEEDB
{
    [DbContext(typeof(RateEEDBContext))]
    [Migration("20260226175436_RateBuild")]
    partial class RateBuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colour");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.InsuranceCover", b =>
                {
                    b.Property<int>("InsuranceCoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceCoverId"));

                    b.Property<string>("InsuranceCoverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceCoverId");

                    b.ToTable("InsuranceCover");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.LicenseDisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleID")
                        .IsUnique();

                    b.ToTable("LicenseDisk");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.Property<int>("PostCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostCheckId"));

                    b.Property<string>("AdditionalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrakeLights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brakes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedByJWSecurity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ClosingKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handbrake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadLights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JWMarketingMagnets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JackAndWheelSpannerPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseDiskValid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mirrors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OilLeaks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkLights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReverseHooter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReverseLight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatBelts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpareWheelPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrobeLight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunVisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("TyreCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindscreenWiper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostCheckId");

                    b.HasIndex("TripId");

                    b.ToTable("PostCheck");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PreChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("BrakeLights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brakes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedByJWSecurity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handbrake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadLights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JWMarketingMagnets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JackAndWheelSpannerPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseDiskValid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mirrors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OilLeaks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OpeningKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ParkLights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReverseHooter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReverseLight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatBelts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpareWheelPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrobeLight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunVisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyreCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindscreenWiper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingID");

                    b.ToTable("PreChecklist");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("ActivityCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobNo")
                        .HasColumnType("int");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TaskCode")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("StatusId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Rate", b =>
                {
                    b.Property<int>("RateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateID"));

                    b.Property<string>("ApplicableTimePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("RateTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RateID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("RateTypeID");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RateType", b =>
                {
                    b.Property<int>("RateTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateTypeID"));

                    b.Property<string>("RateTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RateTypeID");

                    b.ToTable("RateType");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RatesEE", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RateId");

                    b.HasIndex("ProjectId", "IsActive");

                    b.ToTable("RatesEE");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RefuelVehicle", b =>
                {
                    b.Property<int>("RefuelVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefuelVehicleId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FuelCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FuelQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OilLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("TyreCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyrePressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefuelVehicleId");

                    b.HasIndex("TripId");

                    b.ToTable("RefuelVehicle");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreChecklistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TravelStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.HasIndex("BookingID");

                    b.HasIndex("PreChecklistId");

                    b.HasIndex("VehicleID");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.TripMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCheckId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.HasIndex("PostCheckId");

                    b.ToTable("TripMedia");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"));

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColourID")
                        .HasColumnType("int");

                    b.Property<string>("Compliance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuelTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("HasCanopy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTowBar")
                        .HasColumnType("bit");

                    b.Property<int>("InsuranceCoverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleMakeID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelID")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleID");

                    b.HasIndex("ColourID");

                    b.HasIndex("FuelTypeID");

                    b.HasIndex("InsuranceCoverID");

                    b.HasIndex("StatusID");

                    b.HasIndex("VehicleMakeID");

                    b.HasIndex("VehicleModelID");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleFuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FuelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleFuelType");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleMakeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleMakeID");

                    b.ToTable("VehicleMake");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelID"));

                    b.Property<int>("VehicleMakeID")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleModelID");

                    b.HasIndex("VehicleMakeID");

                    b.ToTable("VehicleModel");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Project", "Project")
                        .WithMany("Bookings")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("Team34FinalAPI.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Status");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.LicenseDisk", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Vehicle", null)
                        .WithOne("LicenseDisk")
                        .HasForeignKey("Team34FinalAPI.Models.LicenseDisk", "VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Trip", "Trip")
                        .WithMany("PostChecks")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PreChecklist", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Booking", "Booking")
                        .WithMany("PreChecklists")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Rate", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Project", "Project")
                        .WithMany("Rates")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.RateType", "RateType")
                        .WithMany("Rates")
                        .HasForeignKey("RateTypeID");

                    b.Navigation("Project");

                    b.Navigation("RateType");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RatesEE", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Project", "Project")
                        .WithMany("RatesEE")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RefuelVehicle", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Trip", "Trip")
                        .WithMany("RefuelVehicles")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Booking", "Booking")
                        .WithMany("Trips")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.PreChecklist", "PreChecklist")
                        .WithMany()
                        .HasForeignKey("PreChecklistId");

                    b.HasOne("Team34FinalAPI.Models.Vehicle", null)
                        .WithMany("Trips")
                        .HasForeignKey("VehicleID");

                    b.Navigation("Booking");

                    b.Navigation("PreChecklist");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.TripMedia", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.PostCheck", "PostCheck")
                        .WithMany("TripMedia")
                        .HasForeignKey("PostCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostCheck");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Vehicle", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.VehicleFuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.InsuranceCover", "InsuranceCover")
                        .WithMany()
                        .HasForeignKey("InsuranceCoverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("VehicleMakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("FuelType");

                    b.Navigation("InsuranceCover");

                    b.Navigation("Status");

                    b.Navigation("VehicleMake");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleModel", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("VehicleMakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMake");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.Navigation("PreChecklists");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.Navigation("TripMedia");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rates");

                    b.Navigation("RatesEE");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RateType", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.Navigation("PostChecks");

                    b.Navigation("RefuelVehicles");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LicenseDisk")
                        .IsRequired();

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
