// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team34FinalAPI.Models;

#nullable disable

namespace Team34FinalAPI.Migrations.VehicleDb
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20250605215122_Apollo-ZeroTrust")]
    partial class ApolloZeroTrust
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colour");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = " Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = " White "
                        },
                        new
                        {
                            Id = 3,
                            Name = " Blue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 5,
                            Name = " Grey"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 7,
                            Name = " Silver"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.InsuranceCover", b =>
                {
                    b.Property<int>("InsuranceCoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceCoverId"));

                    b.Property<string>("InsuranceCoverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceCoverId");

                    b.ToTable("InsuranceCover");

                    b.HasData(
                        new
                        {
                            InsuranceCoverId = 1,
                            InsuranceCoverName = " By Seun"
                        },
                        new
                        {
                            InsuranceCoverId = 2,
                            InsuranceCoverName = "Comprehensive "
                        },
                        new
                        {
                            InsuranceCoverId = 3,
                            InsuranceCoverName = " Third-party "
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.LicenseDisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleID")
                        .IsUnique();

                    b.ToTable("LicenseDisks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicenseExpiryDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 1
                        },
                        new
                        {
                            Id = 2,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 2
                        },
                        new
                        {
                            Id = 3,
                            LicenseExpiryDate = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 3
                        },
                        new
                        {
                            Id = 4,
                            LicenseExpiryDate = new DateTime(2028, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 4
                        },
                        new
                        {
                            Id = 5,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 5
                        },
                        new
                        {
                            Id = 6,
                            LicenseExpiryDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 6
                        },
                        new
                        {
                            Id = 7,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 7
                        },
                        new
                        {
                            Id = 8,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 8
                        },
                        new
                        {
                            Id = 9,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 9
                        },
                        new
                        {
                            Id = 10,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 10
                        },
                        new
                        {
                            Id = 11,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 11
                        },
                        new
                        {
                            Id = 12,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 12
                        },
                        new
                        {
                            Id = 13,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 13
                        },
                        new
                        {
                            Id = 14,
                            LicenseExpiryDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 14
                        },
                        new
                        {
                            Id = 15,
                            LicenseExpiryDate = new DateTime(2028, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 15
                        },
                        new
                        {
                            Id = 16,
                            LicenseExpiryDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 16
                        },
                        new
                        {
                            Id = 17,
                            LicenseExpiryDate = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 17
                        },
                        new
                        {
                            Id = 18,
                            LicenseExpiryDate = new DateTime(2028, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 18
                        },
                        new
                        {
                            Id = 19,
                            LicenseExpiryDate = new DateTime(2027, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 19
                        },
                        new
                        {
                            Id = 20,
                            LicenseExpiryDate = new DateTime(2028, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 20
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.Property<int>("PostCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostCheckId"));

                    b.Property<string>("AdditionalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BrakeLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Brakes")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedByJWSecurity")
                        .HasColumnType("bit");

                    b.Property<decimal>("ClosingKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FuelLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("Handbrake")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Horn")
                        .HasColumnType("bit");

                    b.Property<bool>("Indicators")
                        .HasColumnType("bit");

                    b.Property<bool>("JWMarketingMagnets")
                        .HasColumnType("bit");

                    b.Property<bool>("JackAndWheelSpannerPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("LicenseDiskValid")
                        .HasColumnType("bit");

                    b.Property<bool>("Mirrors")
                        .HasColumnType("bit");

                    b.Property<bool>("OilLeaks")
                        .HasColumnType("bit");

                    b.Property<bool>("ParkLights")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseHooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SeatBelts")
                        .HasColumnType("bit");

                    b.Property<bool>("SpareWheelPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("StrobeLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SunVisor")
                        .HasColumnType("bit");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<bool>("TyreCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("WindscreenWiper")
                        .HasColumnType("bit");

                    b.HasKey("PostCheckId");

                    b.HasIndex("TripId");

                    b.ToTable("PostCheck");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostChecklist", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<decimal>("ClosingKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ReturnVehicle")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("VehicleId");

                    b.ToTable("PostChecklist");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostDocumentation", b =>
                {
                    b.Property<bool>("CheckedBySecurity")
                        .HasColumnType("bit");

                    b.Property<bool>("LicenseDisks")
                        .HasColumnType("bit");

                    b.ToTable("PostDocumentation");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PreChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<bool>("BrakeLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Brakes")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedByJWSecurity")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FuelLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("Handbrake")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadLights")
                        .HasColumnType("bit");

                    b.Property<bool>("Horn")
                        .HasColumnType("bit");

                    b.Property<bool>("Indicators")
                        .HasColumnType("bit");

                    b.Property<bool>("JWMarketingMagnets")
                        .HasColumnType("bit");

                    b.Property<bool>("JackAndWheelSpannerPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("LicenseDiskValid")
                        .HasColumnType("bit");

                    b.Property<bool>("Mirrors")
                        .HasColumnType("bit");

                    b.Property<bool>("OilLeaks")
                        .HasColumnType("bit");

                    b.Property<decimal>("OpeningKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ParkLights")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseHooter")
                        .HasColumnType("bit");

                    b.Property<bool>("ReverseLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SeatBelts")
                        .HasColumnType("bit");

                    b.Property<bool>("SpareWheelPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("StrobeLight")
                        .HasColumnType("bit");

                    b.Property<bool>("SunVisor")
                        .HasColumnType("bit");

                    b.Property<bool>("TyreCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("WindscreenWiper")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BookingID");

                    b.ToTable("PreChecklist");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("ActivityCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobNo")
                        .HasColumnType("int");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TaskCode")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("StatusId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Rate", b =>
                {
                    b.Property<int>("RateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateID"));

                    b.Property<string>("ApplicableTimePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RateID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RefuelVehicle", b =>
                {
                    b.Property<int>("RefuelVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefuelVehicleId"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FuelCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FuelQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OilLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<string>("TyreCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TyrePressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefuelVehicleId");

                    b.HasIndex("TripId");

                    b.ToTable("RefuelVehicle");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.HasAlternateKey("VehicleID");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            AdminEmail = "u22492161@tuks.co.za",
                            AdminName = "Busi",
                            Description = " Doors not closing",
                            ServiceDate = new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 1
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.ServiceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceHistory");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Available"
                        },
                        new
                        {
                            Id = 2,
                            DateChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Booked"
                        },
                        new
                        {
                            Id = 3,
                            DateChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "In For Service"
                        },
                        new
                        {
                            Id = 4,
                            DateChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 5,
                            DateChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Active"
                        },
                        new
                        {
                            Id = 6,
                            DateChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Complete"
                        },
                        new
                        {
                            Id = 7,
                            DateChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "In-Progress"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreChecklistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TravelStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.HasIndex("BookingID");

                    b.HasIndex("PreChecklistId");

                    b.HasIndex("VehicleID");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.TripMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostCheckId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.HasIndex("PostCheckId");

                    b.ToTable("TripMedia");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"));

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ColourID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EngineNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuelTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("HasCanopy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasTowBar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("InsuranceCoverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleMakeID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelID")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CASE \r\n        WHEN Description LIKE '%DC%' THEN 'Double Cab'\r\n        WHEN Description LIKE '%SC%' THEN 'Single Cab'\r\n        WHEN Description LIKE '%Extra Cab%' THEN 'Extra Cab'\r\n        ELSE 'Other'\r\n    END");

                    b.HasKey("VehicleID");

                    b.HasIndex("ColourID");

                    b.HasIndex("FuelTypeID");

                    b.HasIndex("InsuranceCoverID");

                    b.HasIndex("StatusID");

                    b.HasIndex("VehicleMakeID");

                    b.HasIndex("VehicleModelID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleID = 1,
                            CabinType = "Hatch",
                            ColourID = 2,
                            DateAcquired = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "i20",
                            DriveType = "4x2",
                            EngineNo = "G4LFPV302509",
                            FuelTypeID = 1,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hyundai 1",
                            RegistrationNumber = "LN 68 YM GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "MALBG512LPM254886",
                            VehicleMakeID = 7,
                            VehicleModelID = 7
                        },
                        new
                        {
                            VehicleID = 2,
                            CabinType = "Extra",
                            ColourID = 2,
                            DateAcquired = new DateTime(2019, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Extra Cab 2.4 GD-6 RB SRX 6MT ",
                            DriveType = "4x2",
                            EngineNo = "2GDC598667",
                            FuelTypeID = 2,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 1",
                            RegistrationNumber = "JF 72 WJ GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB8DC404730166",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 3,
                            CabinType = "Extra",
                            ColourID = 2,
                            DateAcquired = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Extra Cab 2.4 GD-6 RB SRX 6MT",
                            DriveType = "4x2",
                            EngineNo = "2GDC765766",
                            FuelTypeID = 2,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 2",
                            RegistrationNumber = "JT 99 LF GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB3DCX04490835",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 4,
                            CabinType = "Double",
                            ColourID = 2,
                            DateAcquired = new DateTime(2024, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC HILUX 2.4 GD-6 RAIDER 4X4 A/T",
                            DriveType = "4x4",
                            EngineNo = "2GDD364709",
                            FuelTypeID = 2,
                            HasCanopy = false,
                            HasTowBar = true,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2028, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 3",
                            RegistrationNumber = "LR 01 CT GP",
                            StatusID = 1,
                            Transmission = "Automatic",
                            VIN = "AHTKB3CD802676867",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 5,
                            CabinType = "Single",
                            ColourID = 2,
                            DateAcquired = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD6 RB SRX MT (Z50) 2019",
                            DriveType = "4x2",
                            EngineNo = "2GDC503748",
                            FuelTypeID = 2,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 4",
                            RegistrationNumber = "HY 06 DR GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB8DB104579407",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 6,
                            CabinType = "Double",
                            ColourID = 2,
                            DateAcquired = new DateTime(2012, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC, Raider 2.7 D, 4X4, ROPS ",
                            DriveType = "4x4",
                            EngineNo = "2KD5635798",
                            FuelTypeID = 1,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2028, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 5",
                            RegistrationNumber = "BT 11 SL GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTFR22G906054497",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 7,
                            CabinType = "Extra",
                            ColourID = 7,
                            DateAcquired = new DateTime(2005, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC",
                            DriveType = "4x2",
                            EngineNo = "1KD7486383",
                            FuelTypeID = 1,
                            HasCanopy = false,
                            HasTowBar = true,
                            InsuranceCoverID = 3,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 6",
                            RegistrationNumber = "WZV 941 GP",
                            StatusID = 1,
                            Transmission = "Automatic",
                            VIN = "AHTEZ39G207010469",
                            VehicleMakeID = 11,
                            VehicleModelID = 7
                        },
                        new
                        {
                            VehicleID = 8,
                            CabinType = "Double",
                            ColourID = 2,
                            DateAcquired = new DateTime(2016, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC, 4X4 ( With Canopy ) ",
                            DriveType = "4x4",
                            EngineNo = "2GD0195958",
                            FuelTypeID = 2,
                            HasCanopy = true,
                            HasTowBar = true,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 7",
                            RegistrationNumber = "FN 57 RR GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTKB3CD302604992",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 9,
                            CabinType = "Double",
                            ColourID = 2,
                            DateAcquired = new DateTime(2016, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "DC, 4x4",
                            DriveType = "4x4",
                            EngineNo = "2GD0207661",
                            FuelTypeID = 2,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 8",
                            RegistrationNumber = "FN 57 ST GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTK3CD202605213",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 10,
                            CabinType = "Double",
                            ColourID = 2,
                            DateAcquired = new DateTime(2017, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "2.8 GD-6DC, 4x4 Auto ( With Canopy ) ",
                            DriveType = "4x4",
                            EngineNo = "1GD0252789",
                            FuelTypeID = 2,
                            HasCanopy = true,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 9",
                            RegistrationNumber = "FV 25 XR GP",
                            StatusID = 1,
                            Transmission = "Automatic",
                            VIN = "AHTHA3CD403417011",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 11,
                            CabinType = "Single",
                            ColourID = 2,
                            DateAcquired = new DateTime(2017, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD-6RB, SRX 4x2 ",
                            DriveType = "4x2",
                            EngineNo = "2GD0284816",
                            FuelTypeID = 1,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 10",
                            RegistrationNumber = "FX 22 YD GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB8DB504573626",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 12,
                            CabinType = "Single",
                            ColourID = 2,
                            DateAcquired = new DateTime(2017, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " SC 2.4 GD-6RB, SRX 4x2 ",
                            DriveType = "4x2",
                            EngineNo = "2GD0284247",
                            FuelTypeID = 1,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 11",
                            RegistrationNumber = "FX 23 BX GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB8DB304573608",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 13,
                            CabinType = "Double",
                            ColourID = 2,
                            DateAcquired = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " DC 2.4 GD-6RB SR MT ",
                            DriveType = "4x2",
                            EngineNo = "2GDC910427",
                            FuelTypeID = 1,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 12",
                            RegistrationNumber = "KP 05 MC GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB3DD504527511",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 14,
                            CabinType = "Double",
                            ColourID = 2,
                            DateAcquired = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " DC 2.4 GD6 RB RAI MT ( With Canopy ) ",
                            DriveType = "4x2",
                            EngineNo = "2GDD036238",
                            FuelTypeID = 2,
                            HasCanopy = true,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 13",
                            RegistrationNumber = "KW 51 TL GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB3DD304529631",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 15,
                            CabinType = "Extra",
                            ColourID = 2,
                            DateAcquired = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Extra Cab HiluxXC 2.4 GD6 RBRAI 6MT ( A1P )  ",
                            DriveType = "4x2",
                            EngineNo = "2GDD138062",
                            FuelTypeID = 2,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 14",
                            RegistrationNumber = "LB 93 JV GP",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "AHTJB3DC104496782",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 16,
                            CabinType = "SUV",
                            ColourID = 2,
                            DateAcquired = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "SUV 1.8 XR CVT ",
                            DriveType = "4x2",
                            EngineNo = "2ZRW975634",
                            FuelTypeID = 2,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota 15",
                            RegistrationNumber = "KV 84 DV GP ",
                            StatusID = 1,
                            Transmission = "Automatic",
                            VIN = "AHTKFBAG500614236",
                            VehicleMakeID = 11,
                            VehicleModelID = 2
                        },
                        new
                        {
                            VehicleID = 20,
                            CabinType = "Single",
                            ColourID = 2,
                            DateAcquired = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " DC DMAX 2.2",
                            DriveType = "4x2",
                            EngineNo = "4JK1VT8141",
                            FuelTypeID = 1,
                            HasCanopy = false,
                            HasTowBar = false,
                            InsuranceCoverID = 1,
                            LicenseExpiryDate = new DateTime(2028, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Isuzu 1",
                            RegistrationNumber = " ND 836-010",
                            StatusID = 1,
                            Transmission = "Manual",
                            VIN = "ACVNRCHR3K1070230",
                            VehicleMakeID = 9,
                            VehicleModelID = 2
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("OpeningKms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserName");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleChecklists");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleFuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FuelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FuelName = "Petrol"
                        },
                        new
                        {
                            Id = 2,
                            FuelName = "Diesel"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleMakeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleMakeID");

                    b.ToTable("VehicleMake");

                    b.HasData(
                        new
                        {
                            VehicleMakeID = 1,
                            Name = "Audi"
                        },
                        new
                        {
                            VehicleMakeID = 2,
                            Name = "Brandt BRV"
                        },
                        new
                        {
                            VehicleMakeID = 3,
                            Name = "Citroen"
                        },
                        new
                        {
                            VehicleMakeID = 4,
                            Name = "Ford"
                        },
                        new
                        {
                            VehicleMakeID = 5,
                            Name = "Haval"
                        },
                        new
                        {
                            VehicleMakeID = 6,
                            Name = "Honda"
                        },
                        new
                        {
                            VehicleMakeID = 7,
                            Name = "Hyundai"
                        },
                        new
                        {
                            VehicleMakeID = 8,
                            Name = "Kia"
                        },
                        new
                        {
                            VehicleMakeID = 9,
                            Name = "Isuzu"
                        },
                        new
                        {
                            VehicleMakeID = 10,
                            Name = "Nissan"
                        },
                        new
                        {
                            VehicleMakeID = 11,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelID"));

                    b.Property<int>("VehicleMakeID")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleModelID");

                    b.HasIndex("VehicleMakeID");

                    b.ToTable("VehicleModel");

                    b.HasData(
                        new
                        {
                            VehicleModelID = 1,
                            VehicleMakeID = 11,
                            VehicleModelName = " Corolla Cross"
                        },
                        new
                        {
                            VehicleModelID = 2,
                            VehicleMakeID = 11,
                            VehicleModelName = " Hilux "
                        },
                        new
                        {
                            VehicleModelID = 3,
                            VehicleMakeID = 9,
                            VehicleModelName = " Izuzu"
                        },
                        new
                        {
                            VehicleModelID = 4,
                            VehicleMakeID = 1,
                            VehicleModelName = " A3"
                        },
                        new
                        {
                            VehicleModelID = 5,
                            VehicleMakeID = 1,
                            VehicleModelName = " A4 "
                        },
                        new
                        {
                            VehicleModelID = 6,
                            VehicleMakeID = 7,
                            VehicleModelName = " Grand i10"
                        },
                        new
                        {
                            VehicleModelID = 7,
                            VehicleMakeID = 7,
                            VehicleModelName = " Venue "
                        },
                        new
                        {
                            VehicleModelID = 8,
                            VehicleMakeID = 7,
                            VehicleModelName = " TUCSON"
                        },
                        new
                        {
                            VehicleModelID = 9,
                            VehicleMakeID = 4,
                            VehicleModelName = " Ranger"
                        });
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Project", "Project")
                        .WithMany("Bookings")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("Team34FinalAPI.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Status");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.LicenseDisk", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Vehicle", null)
                        .WithOne("LicenseDisk")
                        .HasForeignKey("Team34FinalAPI.Models.LicenseDisk", "VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Trip", "Trip")
                        .WithMany("PostChecks")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostChecklist", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PreChecklist", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Booking", "Booking")
                        .WithMany("PreChecklists")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Rate", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Project", "Project")
                        .WithMany("Rates")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.RefuelVehicle", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Trip", "Trip")
                        .WithMany("RefuelVehicles")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Booking", "Booking")
                        .WithMany("Trips")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.PreChecklist", "PreChecklist")
                        .WithMany()
                        .HasForeignKey("PreChecklistId");

                    b.HasOne("Team34FinalAPI.Models.Vehicle", null)
                        .WithMany("Trips")
                        .HasForeignKey("VehicleID");

                    b.Navigation("Booking");

                    b.Navigation("PreChecklist");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.TripMedia", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.PostCheck", "PostCheck")
                        .WithMany("TripMedia")
                        .HasForeignKey("PostCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostCheck");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Vehicle", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.VehicleFuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.InsuranceCover", "InsuranceCover")
                        .WithMany()
                        .HasForeignKey("InsuranceCoverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("VehicleMakeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Team34FinalAPI.Models.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("FuelType");

                    b.Navigation("InsuranceCover");

                    b.Navigation("Status");

                    b.Navigation("VehicleMake");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleChecklist", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Team34FinalAPI.Models.Documentation", "Documentation", b1 =>
                        {
                            b1.Property<int>("VehicleChecklistId")
                                .HasColumnType("int");

                            b1.Property<bool>("CheckedBySecurity")
                                .HasColumnType("bit");

                            b1.Property<bool>("LicenseDisks")
                                .HasColumnType("bit");

                            b1.HasKey("VehicleChecklistId");

                            b1.ToTable("VehicleChecklists");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChecklistId");
                        });

                    b.OwnsOne("Team34FinalAPI.Models.ExteriorChecks", "ExteriorChecks", b1 =>
                        {
                            b1.Property<int>("VehicleChecklistId")
                                .HasColumnType("int");

                            b1.Property<bool>("BrakeLights")
                                .HasColumnType("bit");

                            b1.Property<bool>("DamageToInteriorBodywork")
                                .HasColumnType("bit");

                            b1.Property<bool>("HeadLights")
                                .HasColumnType("bit");

                            b1.Property<bool>("MarketingMagnets")
                                .HasColumnType("bit");

                            b1.Property<bool>("Mirrors")
                                .HasColumnType("bit");

                            b1.Property<bool>("OilWaterLeaks")
                                .HasColumnType("bit");

                            b1.Property<bool>("ParkLights")
                                .HasColumnType("bit");

                            b1.Property<bool>("ReverseLight")
                                .HasColumnType("bit");

                            b1.Property<bool>("SpareWheelPresent")
                                .HasColumnType("bit");

                            b1.Property<bool>("StrobeLights")
                                .HasColumnType("bit");

                            b1.Property<bool>("TyreCondition")
                                .HasColumnType("bit");

                            b1.HasKey("VehicleChecklistId");

                            b1.ToTable("VehicleChecklists");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChecklistId");
                        });

                    b.OwnsOne("Team34FinalAPI.Models.FunctionalTests", "FunctionalTests", b1 =>
                        {
                            b1.Property<int>("VehicleChecklistId")
                                .HasColumnType("int");

                            b1.Property<bool>("Brakes")
                                .HasColumnType("bit");

                            b1.Property<bool>("Handbrake")
                                .HasColumnType("bit");

                            b1.Property<bool>("Indicator")
                                .HasColumnType("bit");

                            b1.Property<bool>("ReverseHooter")
                                .HasColumnType("bit");

                            b1.HasKey("VehicleChecklistId");

                            b1.ToTable("VehicleChecklists");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChecklistId");
                        });

                    b.OwnsOne("Team34FinalAPI.Models.InteriorChecks", "InteriorChecks", b1 =>
                        {
                            b1.Property<int>("VehicleChecklistId")
                                .HasColumnType("int");

                            b1.Property<bool>("Horn")
                                .HasColumnType("bit");

                            b1.Property<bool>("Seatbelt")
                                .HasColumnType("bit");

                            b1.Property<bool>("SunVisor")
                                .HasColumnType("bit");

                            b1.Property<bool>("Sunblock")
                                .HasColumnType("bit");

                            b1.Property<bool>("Windscreen")
                                .HasColumnType("bit");

                            b1.HasKey("VehicleChecklistId");

                            b1.ToTable("VehicleChecklists");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChecklistId");
                        });

                    b.OwnsOne("Team34FinalAPI.Models.SafetyEquipment", "SafetyEquipment", b1 =>
                        {
                            b1.Property<int>("VehicleChecklistId")
                                .HasColumnType("int");

                            b1.Property<bool>("FireExtinguisher")
                                .HasColumnType("bit");

                            b1.Property<bool>("InspectionValid")
                                .HasColumnType("bit");

                            b1.Property<bool>("JackWheelPresent")
                                .HasColumnType("bit");

                            b1.Property<bool>("TriangleInPlace3x")
                                .HasColumnType("bit");

                            b1.HasKey("VehicleChecklistId");

                            b1.ToTable("VehicleChecklists");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChecklistId");
                        });

                    b.OwnsOne("Team34FinalAPI.Models.UnderTheHoodChecks", "UnderTheHoodChecks", b1 =>
                        {
                            b1.Property<int>("VehicleChecklistId")
                                .HasColumnType("int");

                            b1.Property<bool>("FuelLevel")
                                .HasColumnType("bit");

                            b1.HasKey("VehicleChecklistId");

                            b1.ToTable("VehicleChecklists");

                            b1.WithOwner()
                                .HasForeignKey("VehicleChecklistId");
                        });

                    b.Navigation("Documentation")
                        .IsRequired();

                    b.Navigation("ExteriorChecks")
                        .IsRequired();

                    b.Navigation("FunctionalTests")
                        .IsRequired();

                    b.Navigation("InteriorChecks")
                        .IsRequired();

                    b.Navigation("SafetyEquipment")
                        .IsRequired();

                    b.Navigation("UnderTheHoodChecks")
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.VehicleModel", b =>
                {
                    b.HasOne("Team34FinalAPI.Models.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("VehicleMakeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMake");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Booking", b =>
                {
                    b.Navigation("PreChecklists");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.PostCheck", b =>
                {
                    b.Navigation("TripMedia");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Project", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Trip", b =>
                {
                    b.Navigation("PostChecks");

                    b.Navigation("RefuelVehicles");
                });

            modelBuilder.Entity("Team34FinalAPI.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LicenseDisk")
                        .IsRequired();

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
